version: '3'

services:

  app:
    build: './src/app'
    volumes:
      - './src/app:/app'

  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '8080:80'
